### ISSUE TITLE
[Feature] RTMP URLs

### ISSUE THREAD

**Issue by cwchristerw** [Walkyst/lavaplayer-fork#13]
I would like to have a way to play RTMP & RTMPS urls.

**Comment by Walkyst** [comment]
Any examples of these links?

**Comment by duncte123** [comment]
> Any examples of these links?

`rtmp://127.0.0.1/path`

you can use the [rtmp module for nginx](https://github.com/arut/nginx-rtmp-module) and [obs](https://obsproject.com/) to experiment with this.
You'll need to set up something yourself because usually these URLs are used for streaming to a platform (and the key is suffixed onto the path)
